---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified
number-sections: true
---


# Useful resources for Data Collection & Managment {#sec-resources}

## R Programming 

### Essential Resources  {.unnumbered}   

1. **_R for Data Science_ book:** Hadley Wickham wrote a book on using the tidyverse and [_the online version is FREE_](https://r4ds.hadley.nz/). This is a phenomenal resource on using R to import, tidy, and visualize data. 

1. [**Posit Cheat Sheets**](https://posit.co/resources/cheatsheets/): help with commands for using the different `tidyverse` packages, RStudio shortcuts and tricks, help with R commands, and more. You definitely want the ones for Data Import, Work with Strings, Factors, Data Transformation, and Base R.

1. **RStudio Keyboard Shortcuts**: A list of the keyboard shortcuts for Mac, Windows, and Linux can be found [here](https://support.posit.co/hc/en-us/articles/200711853-Keyboard-Shortcuts-in-the-RStudio-IDE). 

1. **Where and How to ask for help:**  

  > * Hadley Wickham's advice on [how to write a good reproducible  
  example]((http://adv-r.had.co.nz/Reproducibility.html)) for getting help with R  
  > * [how to post good questions on StackOverflow](https://www.r-bloggers.com/2011/01/three-tips-for-posting-good-questions-to-r-help-and-stack-overflow/)  
  > * The UF [R-users listserv](http://www.r-gators.com/listserv/) is *very* user friendly and a great place to post requests for help. 


### Tutorials {.unnumbered}  

1. [Paul van der Laken's List](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/)  of books, tutorials, and other resources on topics ranging from data manipulation to data validation to data visualization.

1. [R Essential Training: Wrangling and Visualizing Data](https://www.linkedin.com/learning/r-essential-training-wrangling-and-visualizing-data/navigating-the-rstudio-environment?u=41282748). (requires a UF email address to access LinkedIn Learning).

1. Software Carpentry: [Using RStudio for Project Organization & Management](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro.html)

1. [Swirl](https://swirlstats.com/): learn R programming interactively, at your own pace, and in the R console.

1. [R Bootcamp](https://r-bootcamp.netlify.app/) by Ted Laderas and Jessica Minnier. Learn R in your browser.

1. [How to clean messy data in R](https://rfortherestofus.com/2019/12/how-to-clean-messy-data-in-r/) 

1. [The Ultimate Guide to Data Cleaning](https://towardsdatascience.com/the-ultimate-guide-to-data-cleaning-3969843991d4) is written for Python users but the pricniples apply regardless of language.


## Specific Data Cleaning and Management Problems 

### Dates & Times {.unnumbered}  

1. [**Handling dates and times in R**](https://course.naturecast.org/docs/r-time-series-data/r_tutorial/)

### Text & Text Mining {.unnumbered}  

2. **Text Mining:** [`tidytext`](https://juliasilge.github.io/tidytext/) package

### Qualtrics {.unnumbered}  

3. **Working with Qualtrics** survey data: [`qualtRics`](https://docs.ropensci.org/qualtRics/) package

### Text Extraction {.unnumbered}  

4. **Optical Character Recognition (OCR):** extract text from images: [`tesseract`](https://docs.ropensci.org/tesseract/) package

5. **Extract text & metadata from pdf files:** [`pdftools`](https://docs.ropensci.org/pdftools/) package

### Images & Image Processing {.unnumbered}  

6. **Image processing**: the [`magick`](https://cran.r-project.org/web/packages/magick/vignettes/intro.html) package


## Advanced R Packages for Data Management 

1. [`DataCurator`](https://github.com/qcif/data-curator) package: 'a simple desktop data editor to help describe, validate and share usable open data'.

1. [RegExr](https://regexr.com/): online tool to learn, build, & test Regular Expressions (RegEx / RegExp) 

1. [janitor](https://github.com/sfirke/janitor) (cleanup of file names, etc.) 

1. [ROpenSci](https://ropensci.org/): tools for accessing, manipulating, and visualizing open data

## Data Visualization

1. [*Data Visualization: a practical introduction*](https://socviz.co/) by Kieran Healy is my favorite introductory (yet super-comprehensive) book on data visualization with R. If you scroll down to the bottom of the page you can download the datasets and code used to make the figures in the book, which makes life much easier.  

## Slide & Presentations  

1. Make [slide presentations with R](https://rmarkdown.rstudio.com/lesson-11.html)

## Documents & Reports  

1. [`knitr`](https://kbroman.org/knitr_knutshell/pages/overview.html) overview: reproducible documents with R


## Discipline-specific R Resources  

### History   {.unnumbered}    

1. [`historydata`](https://github.com/ropensci/historydata) package: Sample data sets for historians learning R. They include population, institutional, religious, military, and prosopographical data suitable for mapping, quantitative analysis, and network analysis.

2. [*The Programming Historian*](https://programminghistorian.org/) Website: wide range of topics, from text analysis to OpenRefine

### Psychology   {.unnumbered}    

1. ['Programming for Psychologists: Data Creation and Analysis'](https://www.crumplab.com/programmingforpsych/) by Matthew J. C. Crump


## Data Archives 

1. [Qualitative Data Repository](https://qdr.syr.edu/): dedicated archive for storing and sharing digital data (and accompanying documentation) generated or collected through qualitative and multi-method research in the social sciences and related disciplines.

1. [Data Dryad](https://datadryad.org/): open data publishing platform and a community committed to the open availability and routine re-use of all research data.

1. [ICPSR](https://www.icpsr.umich.edu/sites/icpsr/home): data access, curation, and analytical methods for social science.


