project:
  type: book
book:
  title: "HerbVar Project Manual & Field Protocols"
  author: "The Herbvar Steering Committee"
  date: "5/3/2024"
  cover-image: images/cover.png
  # favicon: images/cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - part: "New Collaborators: Getting Started"
      chapters: 
        - onboarding_intro.qmd
        - contacts.qmd
    - part: "Research Workflow" 
      chapters:
        - workflow.qmd
        - data_collection.qmd
        - uploading_data.qmd 
        - data_analysis.qmd
        - publications.qmd
    - part: "Protocols"
      chapters: 
        - protocols/spp_site_selection.qmd
        - protocols/primary.qmd
        - protocols/repro_damage.qmd
        - protocols/damage.qmd
        - protocols/low_density.qmd
        - protocols/succulents.qmd
        - protocols/tree.qmd
        - protocols/rhizo_geo.qmd
        - protocols/herbivore.qmd    
    - part: "Admin Tasks"
      chapters: 
        - potential_collaborators.qmd
        - website.qmd
        - data_portal.qmd
        - google_drive.qmd
        - wrangling_repo.qmd
        - unfinished_tasks.qmd
    - references.qmd
    - part: "Appendix"
      chapters: 
        - herbvar_pubs.qmd
        # - herbvar_presentations.qmd
        
    
# output-file: "HerbVar_Manual"
bibliography: HerbVar.bib
  # - "./protocols/manual.bib"
  # - "project_publications.bib"
  
# csl: ecology.csl
format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
  pdf:
    documentclass: scrreprt
editor: source