project:
  type: book
  output-dir: docs
book:
  title: "HerbVar Project Manual & Field Protocols"
  author: "The Herbvar Steering Committee"
  date: "5/3/2024"
  cover-image: images/cover.png
  # favicon: images/cover.png
  chapters:
    - index.qmd
    # - intro.qmd
    - part: "What is HerbVar?"
      chapters: 
        - introduction/intro.qmd
    - part: "New Collaborators: Start Here"
      chapters: 
        - new_collaborators/onboarding_intro.qmd
        - new_collaborators/site_pi.qmd
        # - new_collaborators/contacts.qmd
    - part: "Collaboration and Authorship Guidelines"
      chapters: 
        - collab_auth/collabo_agreement.qmd
        - collab_auth/authorship_guidelines.qmd
    - part: "Research Workflow" 
      chapters:
        - research/workflow.qmd
        - research/data_collection.qmd
        - research/uploading_data.qmd
        - research/data_analysis.qmd
        - research/publications.qmd
    - part: "Protocols"
      chapters: 
        - protocols/spp_site_selection.qmd
        - protocols/primary.qmd
        - protocols/damage.qmd
        - protocols/repro_damage.qmd
        - protocols/low_density.qmd
        - protocols/succulents.qmd
        - protocols/tree.qmd
        - protocols/rhizo_geo.qmd
        - protocols/herbivore.qmd    
    - part: "Admin Tasks"
      chapters: 
        - admin_tasks/potential_collaborators.qmd
        - admin_tasks/manual.qmd
        - admin_tasks/website.qmd
        - admin_tasks/data_portal.qmd
        - admin_tasks/google_drive.qmd
        - admin_tasks/wrangling_repo.qmd
        - admin_tasks/unfinished_tasks.qmd
    - references.qmd
    - part: "Appendix"
      chapters: 
        - appendix/herbvar_pubs.qmd
# output-file: "HerbVar_Manual"
bibliography: HerbVar.bib
# bibliography: ["manual.bib","project_publications.bib","project_presentations.bib"]
csl: ecology.csl
format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
  pdf:
    # pdf-engine: xelatex
    documentclass: scrreprt
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto