project:
  type: book
book:
  title: "HerbVar Project Manual & Field Protocols"
  author: "The Herbvar Steering Committee"
  date: "5/3/2024"
  cover-image: images/cover.png
  # favicon: images/cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - part: "New Collaborators: Start Here"
      chapters: 
        - new_collaborators/onboarding_intro.qmd
        - new_collaborators/contacts.qmd
    - part: "Research Workflow" 
      chapters:
        - research/workflow.qmd
        - research/data_collection.qmd
        - research/uploading_data.qmd 
        - research/data_analysis.qmd
        - research/publications.qmd
    - part: "Protocols"
      chapters: 
        - protocols/spp_site_selection.qmd
        - protocols/primary.qmd
        - protocols/repro_damage.qmd
        - protocols/damage.qmd
        - protocols/low_density.qmd
        - protocols/succulents.qmd
        - protocols/tree.qmd
        - protocols/rhizo_geo.qmd
        - protocols/herbivore.qmd    
    - part: "Admin Tasks"
      chapters: 
        - admin_tasks/potential_collaborators.qmd
        - admin_tasks/website.qmd
        - admin_tasks/data_portal.qmd
        - admin_tasks/google_drive.qmd
        - admin_tasks/wrangling_repo.qmd
        - admin_tasks/unfinished_tasks.qmd
    - references.qmd
    - part: "Appendix"
      chapters: 
        - herbvar_pubs.qmd
        # - herbvar_presentations.qmd
        
    
# output-file: "HerbVar_Manual"
bibliography: 
  - manual.bib
  - project_publications.bib
# csl: ecology.csl
format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
  pdf:
    documentclass: scrreprt
editor: source

execute:
  freeze: auto