project:
  type: book
  output-dir: docs
  
book:
  title: "HerbVar Project Manual & Field Protocols"
  output-file: "herbvar-manual"
  author: "The Herbvar Steering Committee"
  # date: 11/15/2024
  # doi
  # license
  # url
  date: last-modified
  original-date: 11/15/2024
  date-format: long
  edition: "1st Edition"
  cover-image: images/cover.png
  search: true
  repo-url: https://github.com/HerbVar-Network/herbvar_manual
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  reader-mode: false
  favicon: images/cover.png
  page-footer:
    left: |
      The HerbVar Manual was written by the HerbVar RCN STeering Committee.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    
    - part: "What is HerbVar?"
      chapters: 
        - introduction/intro.qmd
        - introduction/getting_involved.qmd
        - introduction/Network_Structure.qmd
        - introduction/data_overview.qmd
        - introduction/herbvar_pubs.qmd
        
    - part: "Become a Collaborator"
      chapters: 
        - collaboration/site_pi.qmd
        - collaboration/data_use_guidelines.qmd
        - collaboration/new_analyses.qmd
        - collaboration/authorship_process.qmd
        - collaboration/new_data_collection.qmd
        - collaboration/project_review.qmd
        
    - part: "Research Workflow" 
      chapters:
        - workflow/workflow.qmd
        - workflow/data_collection.qmd
        - workflow/uploading_data.qmd
        - workflow/data_analysis.qmd
        - workflow/publications.qmd
        
    - references.qmd
    
    - part: "Appendix 1: Protocols"
      chapters: 
        - protocols/spp_site_selection.qmd
        - protocols/primary.qmd
        - protocols/damage.qmd
        - protocols/repro_damage.qmd
        - protocols/low_density.qmd
        - protocols/succulents.qmd
        - protocols/tree.qmd
        - protocols/rhizo_geo.qmd
        - protocols/herbivore.qmd    
        
    - part: "Appendix 2: Forms & Checklists"
      chapters: 
        - forms/onboarding_intro.qmd
        
    - part: "Appendix 3: HerbVar Admin"
      chapters: 
        - admin/potential_collaborators.qmd
        - admin/manual.qmd
        - admin/website.qmd
        - admin/data_portal.qmd
        - admin/google_drive.qmd
        - admin/wrangling_repo.qmd
        - admin/unfinished_tasks.qmd
    
bibliography: HerbVar.bib
csl: ecology.csl
format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
  pdf:
      documentclass: scrbook
      cover-image: images/cover.png
  epub:
      epub-cover-image: images/cover.png

# pdf-engine: xelatex
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto