project:
  type: book
  output-dir: docs
  
book:
  title: "LAS 6292: Data Collection and Management"
  output-file: "las6202-reader"
  author: "Emilio M. Bruna"
  date: 11/15/2025
  # date: last-modified
  # original-date: 11/15/2024
  # doi
  # url: https://herbvar-network.github.io/herbvar_manual
  # pdf-url: https://herbvar-network.github.io/herbvar_manual/herbvar-manual.pdf 
  date-format: long
  license: "This work is licensed under CC BY-NC-SA 4.0. //To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/"
  edition: "v0.9.0"
  cover-image: images/cover.png
  search: true
  repo-url: https://github.com/HerbVar-Network/herbvar_manual
  repo-actions: [edit]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  reader-mode: false
  favicon: images/cover.png
  page-footer:
    left: |
      LAS 6292 Data Collection and Management Course Reader
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    # 
    # - part: "Course Introduction"
    #   chapters: 
    #     # - introduction/intro.qmd
    #     # - introduction/getting_involved.qmd
    #     # - introduction/Network_Structure.qmd
    #     # - introduction/data_overview.qmd
    #     # - introduction/herbvar_products.qmd
    # 
    - part: "Course Topics" 
      chapters: 
    #     # - ‘Data’ across disciplines
        - course_topics/file_names/naming.qmd
    #     # - File Formats
    #     # - Naming Conventions
    #     # - Data Storage & Security
    #     # - Data structure
    #     # - Format of data and datasets
    #     # - Reproducible Data (Re)organization
    #     # - QA/QC 1: Data Entry & Validation
    #     # - QA/QC 2: Data Correction & Synthesis
    #     # - OpenRefine
    #     # - Visualizing Data to Find Mistakes
    #     # - Documentation, Metadata, & Codebooks
    #     # - Data Sharing, Reuse, & Archives
    #     # - Data Management Plans
    #     # - Efficient Data Collection
    #     # - Transcription & Translation
    #     # - ‘Paperless’ Data Collection
    #     # - Automated Data Extraction
    #     # - Legal & Ethical Issues
    # #     
    # - part: "Assignments"
    #   chapters: 
    #     - assignments/assignments.qmd
        # - collaboration/data_use_guidelines.qmd
        # # - collaboration/new_analyses.qmd
        # - collaboration/authorship_process.qmd
        # - collaboration/working-group-pubs.qmd
        # - collaboration/new_data_collection.qmd
        # - collaboration/project_review.qmd
        
    
    # - references.qmd
    # 
    - part: "Appendix 1: Useful Resources"
      chapters: 
        - resources/resources.qmd
        # - forms/data_sharing_contract.qmd
        # - forms/forms_list.qmd
        # - forms/glossary.qmd
        

    
bibliography: las6292.bib
csl: format/ecology.csl
format:

  html:
    theme: 
      - cosmo
      - format/r4ds.scss
      
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    cover-image: images/cover2.png
    # template-partials:
    #   - "protocols/title.tex"
    # header-includes: |
    #    \titlehead{\includegraphics[height=9in]{images/cover2.png}}
    toc: true
    toc-depth: 2
    toc-title: Table of Contents
    lof: true
    lot: true
    bibliography: las6292.bib
    # Numbering
    number-sections: true
    # Fonts
    # fontfamily: libertinus
    # mainfont: Georgia
    # sansfont: Verdana
    # monofont: Source Code Pro
    # fontsize: 12pt
    microtypeoptions: ["final"]
    # Colors
    colorlinks: true
    # Layout
    geometry:
      - margin=1in
      - bindingoffset=0.5in
      # - left=24mm
      # - top=24mm
      # - bottom=24mm 
      # - right=50mm
      # - heightrounded
      # - footskip=0.475in
      # - showframe
    # pagestyle: plain
    # Rendering
    keep-tex: true
    # https://quarto.org/docs/journals/templates.html#template-partials
    # https://github.com/quarto-dev/quarto-cli/discussions/1941
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://github.com/nmfs-opensci/quarto_titlepages_v1
    # https://nmfs-opensci.github.io/quarto_titlepages_v1/03-how-to-use.html
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://nrennie.rbind.io/blog/pdf-quarto/making-pretty-pdf-quarto/
    # https://github.com/nrennie/PrettyPDF

    # include-in-header: 
    #  - "format/PrettyPDF.tex"
    # include-before-body:
    #  - "format/pagestyle.tex
    #   - "format/_titlepage.tex" 
  
      
  epub:
      epub-cover-image: images/cover.png

# pdf-engine: xelatex
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto