project:
  type: book
  output-dir: docs
book:
  title: "HerbVar Project Manual & Field Protocols"
  author: "The Herbvar Steering Committee"
  date: "5/3/2024"
  cover-image: images/cover.png
  # favicon: images/cover.png
  chapters:
    - index.qmd
    # - intro.qmd
    - part: "What is HerbVar?"
      chapters: 
        - introduction/intro.qmd
        - introduction/getting_involved.qmd
        - introduction/Network_Structure.qmd
        - introduction/data_overview.qmd
        - introduction/herbvar_pubs.qmd
    - part: "Collaboration & Authorship Guidelines"
      chapters: 
        - collab_auth/site_pi.qmd
        - collab_auth/data_use_guidelines.qmd
        - collab_auth/authorship_overview.qmd
        - collab_auth/collabo_agreement.qmd
        - collab_auth/authorship_guidelines.qmd
        - collab_auth/new_projects.qmd
        - collab_auth/project_review.qmd
    - part: "Research Workflow" 
      chapters:
        - research/workflow.qmd
        - research/data_collection.qmd
        - research/uploading_data.qmd
        - research/data_analysis.qmd
        - research/publications.qmd
    - references.qmd
    - part: "Appendix 1: Protocols"
      chapters: 
        - protocols/spp_site_selection.qmd
        - protocols/primary.qmd
        - protocols/damage.qmd
        - protocols/repro_damage.qmd
        - protocols/low_density.qmd
        - protocols/succulents.qmd
        - protocols/tree.qmd
        - protocols/rhizo_geo.qmd
        - protocols/herbivore.qmd    
    - part: "Appendix 2: Forms & Checklists"
      chapters: 
        - forms/onboarding_intro.qmd
    - part: "Appendix 3: HerbVar Admin"
      chapters: 
        - admin/potential_collaborators.qmd
        - admin/manual.qmd
        - admin/website.qmd
        - admin/data_portal.qmd
        - admin/google_drive.qmd
        - admin/wrangling_repo.qmd
        - admin/unfinished_tasks.qmd
    
# output-file: "HerbVar_Manual"
bibliography: HerbVar.bib
# bibliography: ["manual.bib","project_publications.bib","project_presentations.bib"]
csl: ecology.csl
format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
  pdf:
    # pdf-engine: xelatex
    documentclass: scrreprt
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto