project:
  type: book
  output-dir: docs

profile:
  default: book
  group:
    - [book, slides]

book:
  title: "LAS 6292: Data Collection and Management"
  subtitle: "Course Reader & Class Notes"
  output-file: "las6292-reader"
  author: "Emilio M. Bruna"
  date: 11/15/2026
  # date: last-modified
  # original-date: 11/15/2024
  # doi
  url: https://brunalab.github.io/LAS6292_DataCourseBook/
  pdf-url: https://brunalab.github.io/LAS6292_DataCourseBook/las6292-reader.pdf 
  date-format: long
  license: "This work is licensed under CC BY-NC-SA 4.0. //To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/"
  edition: "v0.9.0"
  cover-image: images/cover.png
  search: true
  repo-url: https://github.com/BrunaLab/LAS6292_DataCourseBook/
  repo-actions: [edit]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  reader-mode: false
  favicon: images/cover.png
  page-footer:
    left: |
      LAS 6292 Course Reader //& Class Notes
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    # - las6292_syllabus.qmd
    - part: "Course Topics" 
      chapters: 
        #- ‘Data’ across disciplines
        - class_materials/class_sessions/02_file_names/naming.qmd
        - class_materials/class_sessions/02_file_organization/organization.qmd
        - class_materials/class_sessions/02_file_storage/storage.qmd  
        - class_materials/class_sessions/03_spreadsheets/spreadsheets.qmd
        - class_materials/class_sessions/04_reproducibility/reproducibility.qmd
        - class_materials/class_sessions/05_QAQC1/qaqc1.qmd
        - class_materials/class_sessions/06_QAQC2/openrefine.qmd  # - OpenRefine
        #- class_materials/class_sessions/07_QAQC3/error_viz.qmd # - Visualizing Data to Find Mistakes
        - class_materials/class_sessions/08_metadata/metadata.qmd  # - Documentation, Metadata, & Codebooks
        - class_materials/class_sessions/09_DMP/dmp.qmd  # - Data Sharing, Reuse, & Archives
        #- class_materials/class_sessions/0  # - Data Management Plans
        #- class_materials/class_sessions/0  # - Efficient Data Collection
        - class_materials/class_sessions/12_transcription_translation/transcription_translation.qmd  # - Transcription & Translation
        - class_materials/class_sessions/13_paperless_data_collection/paperless.qmd  # - ‘Paperless’ Data Collection
        - class_materials/class_sessions/14_automated_data_extraction/automated.qmd  # - Automated Data Extraction
        - class_materials/class_sessions/15_legal_ethical/legal_ethical.qmd  # - Legal & Ethical Issues

    
    - part: "Class Notes & Activities"
      chapters:
        - class_materials/class_sessions/01_course_introduction/introduction_class.qmd
        - class_materials/class_sessions/02_file_organization/organization_backup_class.qmd
        - class_materials/class_sessions/03_spreadsheets/spreadsheets_class.qmd
        - class_materials/class_sessions/01_course_introduction/introduction_class.qmd
        - class_materials/class_sessions/01_course_introduction/introduction_hw.qmd
    #   - class_materials/class_sessions/02_file_names/naming.qmd
    #   - class_materials/class_sessions/02_file_formats.qmd 
    #   - class_materials/class_sessions/0     Naming Conventions
    #   - class_materials/class_sessions/0  # - Data Storage & Security
        - class_materials/class_sessions/03_spreadsheets/spreadsheets_class.qmd
        - class_materials/class_sessions/03_spreadsheets/spreadsheets_hw.qmd
    #   - class_materials/class_sessions/0  # - Format of data and datasets
        - class_materials/class_sessions/04_reproducibility/reproducibility_hw.qmd
        - class_materials/class_sessions/05_QAQC1/qaqc1_hw.qmd
        - class_materials/class_sessions/06_QAQC2/openrefine_class.qmd  # - OpenRefine
    #   - class_materials/class_sessions/0  # - Visualizing Data to Find Mistakes
    #   - class_materials/class_sessions/0  # - Documentation, Metadata, & Codebooks
    #   - class_materials/class_sessions/0  # - Data Sharing, Reuse, & Archives
    #   - class_materials/class_sessions/0  # - Data Management Plans
    #   - class_materials/class_sessions/0  # - Efficient Data Collection
    #   - class_materials/class_sessions/0  # - Transcription & Translation
    #   - class_materials/class_sessions/0  # - ‘Paperless’ Data Collection
    #   - class_materials/class_sessions/0  # - Automated Data Extraction
    #   - class_materials/class_sessions/0  # - Legal & Ethical Issues
    
    
    - part: "Individual Projects"
      chapters: 
        - class_materials/individual_projects/assignments.qmd
        # - class_materials/individual_projects/data_cleanup.Rmd
        # - class_materials/individual_projects/dmp.Rmd
    
    
    # - references.qmd
    # 
    - part: "Useful Resources"
      chapters: 
        - class_materials/resources/resources.qmd
        - slidedecks.qmd
        # - forms/data_sharing_contract.qmd
        # - forms/forms_list.qmd
        # - forms/glossary.qmd
        

    
bibliography: las6292.bib
csl: format/ecology.csl
format:
  html:
    theme: 
      - cosmo
      - format/r4ds.scss
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    cover-image: images/cover.png
    template-partials:
      - "format/title.tex"
    header-includes: |
       \titlehead{\includegraphics[height=5in]{images/cover.png}}
    toc: true
    toc-depth: 2
    toc-title: Table of Contents
    lof: false
    lot: false
    bibliography: las6292.bib
    # Numbering
    number-sections: true
    # Fonts
    # fontfamily: libertinus
    # mainfont: Georgia
    # sansfont: Verdana
    # monofont: Source Code Pro
    # fontsize: 12pt
    microtypeoptions: ["final"]
    # Colors
    colorlinks: true
    # Layout
    geometry:
      - margin=1in
      - bindingoffset=0.5in
      # - left=24mm
      # - top=24mm
      # - bottom=24mm 
      # - right=50mm
      # - heightrounded
      # - footskip=0.475in
      # - showframe
    # pagestyle: plain
    # Rendering
    keep-tex: true
    # https://quarto.org/docs/journals/templates.html#template-partials
    # https://github.com/quarto-dev/quarto-cli/discussions/1941
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://github.com/nmfs-opensci/quarto_titlepages_v1
    # https://nmfs-opensci.github.io/quarto_titlepages_v1/03-how-to-use.html
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://nrennie.rbind.io/blog/pdf-quarto/making-pretty-pdf-quarto/
    # https://github.com/nrennie/PrettyPDF

    # include-in-header: 
    #  - "format/PrettyPDF.tex"
    # include-before-body:
    #  - "format/pagestyle.tex
    #   - "format/_titlepage.tex" 
  
      
  epub:
      epub-cover-image: images/cover.png

# pdf-engine: xelatex
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto