
# Preamble {.unnumbered}

This book is a manual for students in LAS 6292: Data Collection & Management. The course is designed for graduate students from any discipline – social sciences, humanities, biophysical sciences – and at all stages of their graduate program. It is an introduction to methods for collecting, organizing, managing, and visualizing both qualitative and quantitative data. Students will gain hands-on experience with best practices and tools.

<!-- {{< fa rotate-right >}}  -->
{{< fa comment >}} Describe the different types of research data & the research data life-cycle

{{< fa question >}} Explain the need for and benefits of data management and sharing

{{< fa clipboard-list >}} Describe and implement best practices for data collection, storage, management, and sharing

{{< fa file-download >}} Find, download, and analyze publicly available data from repositories

{{< fa check-double >}} Carry out simple and reproducible data corrections and dataset organization

{{< fa landmark >}} Describe public policies and agency requirements for data management and sharing

{{< fa balance-scale >}} Articulate the major legal & ethical issues regarding the data collection, use, and storage

{{< fa folder-open >}} Create and Implement Data Management Plans in funder-specific formats

{{< fa tools >}} Identify and properly use tools for more efficient and secure data collection in the field

<!-- Describe the different types of research data & the research data life-cycle - -->

<!-- Explain the need for and benefits of data management and sharing -->

<!-- Describe and implement best practices for data collection, storage, management, and sharing -->

<!-- Find, download, and analyze publicly available data from repositories -->

<!-- Carry out simple and reproducible data corrections and dataset organization -->

<!-- Describe public policies and agency requirements for data management and sharing -->

<!-- Articulate the major legal & ethical issues regarding the data collection, use, and storage -->

<!-- Create and Implement Data Management Plans in funder-specific formats -->

<!-- Identify and properly use tools for more efficient and secure data collection in the field -->

---



::: {.callout-tip}
### Citation


<!-- HerbVar Steering Committee (Eds.). 2024. _HerbVar: Project Manual and Field protocols (v0.9.0)_. Zenodo. https://doi.org/10.5281/zenodo.14232308 -->

:::

--- 

This guide is a [Quarto Book](https://quarto.org/docs/books) hosted on the [Bruna Lab's Github site](https://github.com/BrunaLab). Please suggest edits to the text, missing resources, or make suggestions for improvement either by [pull request](https://github.com/BrunaLab/LAS6292_DataCourseBook/pulls) or by [posting an issue](https://github.com/BrunaLab/LAS6292_DataCourseBook/issues) on the course book's repository. For more information and tutorials for doing so, see @sec-manual. 
