---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---


# Metadata  


::: {.callout-tip}

## Objectives and Competencies


By the end of this lesson students will:

  * Be able to explain what metadata are and why they are important
  * Identify & list the types of information typically included in metadata records
  * Identify reasons metadata is of value to data users, creators, and organizations
  * Be able to identify metadata standards relevant to different disciplines
  * Explain the elements of good metadata

:::


## Pre-Class Preparation & Materials Needed (Instructor):

* email students: confirmation of room and zoom link, pls bring own mug or water bottle, welcome to bring food / snacks
* Ask if any students need laptop, arrange for a loan if needed
* Copy of syllabus and Course Roster
* Flip charts, markers, tent cards for names, dry-write markers

## Pre-class Preparation (Students):

### **Readings** {.unnumbered}  

1.  Michener, W.K., et al . 1997. Non-geospatial metadata for the ecological sciences. Ecological Applications 7: 330–342.  
        [[read online]](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/1051-0761%281997%29007%5B0330%3ANMFTES%5D2.0.CO%3B2)  

<!-- 2.  Pp 446-450 in Bernard, H.R. and Bernard, H.R., 2013. Social research methods: Qualitative and quantitative approaches. Sage.  [[download pdf]] -->


### **Online Lectures:**   {.unnumbered}  

* [Metadata](https://youtu.be/wrt-3l71DJ4)


## **Introduction: Metadata**   {.unnumbered}

Data repositories such as [Dryad](https://datadryad.org) and [ICPSR](https://www.icpsr.umich.edu/web/pages/) are designed to permanently store the data thatused in research so it is available to future scholars. To use the data, it is important to have good metadata....but how good are the metadata, really?

*Here is an example from Dryad: The Page ["Data from: Resilient networks of ant-plant mutualists in Amazonian forest fragments"](https://datadryad.org/stash/dataset/doi:10.5061/dryad.pf2r0) includes an overview of the project and dataset, along with some other information. If you click "Download Dataset" you will get a zip file with data in .csv format and the Metadata in .txt format].


## Breakout 1: Metadata Review 

Follow the links to the page below, where you will find the data and metadata from some previously published papers. Rewview the data and metadata and discuss the following:

1. Can you explain the variables they collected?

2. Do the data and metadata appear to adhere to the FAIR Principles? 
  
    * Findable: persistent identifiers & basic machine-actionable metadata
    * Accessible: can be read by machines & humans
    * Interoperable: use shared vocabularies / ontologies, machine-accessible (meta)data
    * Re-Usable: descriptions allow others to reuse and link with other data sources

2. Did they include the 5 metadata descriptors?

    * Class I: alert potential secondary users to the existence of data sets that fall within specific temporal, spatial, and thematic domains. 
    * Class II: describe the research resulting in a data set. 
    * Class III: status of the data set and information on its accessibility. 
    * Class IV: all the attributes related to the structure of the data file. 
    * Class V: all other related information that might be necessary for secondary usage, publishing the data set, or auditing the data set. 

3. Does anything else stand out about the data metadata files? For example...

    * Could you explain what the abbreviations are? 
    * Could you explain how the data were collected? 
    * Could you explain what the values represent? 
    * Could you recreate the analysis? 
    * Is there anything missing from the metadata or that stands out about how they were prepared?


### (Meta)Data Sets {.unnumbered} 

For Numbers 1-4, click on the light blue box with an arrow in the upper right corner that says "Download dataset". 

1. [Data from: Mammal diversity and metacommunity dynamics in urban green spaces: implications for urban wildlife conservation](https://datadryad.org/stash/dataset/doi:10.5061/dryad.9mf02)

2. [Data from: The avifauna of the Galapagos Islands](https://datadryad.org/stash/dataset/doi:10.5061/dryad.156)

3. [Data from: Effect of mutualist partner identity on plant demography](https://datadryad.org/stash/dataset/doi:10.5061/dryad.5kc45)

4. [Data from: Elevated pCO2 affects tissue biomass composition, but not calcification, in a reef coral under two light regimes](https://datadryad.org/stash/dataset/doi:10.5061/dryad.5vg70)

For #5 you should be able to click on the button to the right that sats "Preview this file".

5. [Data from: The moral philosophy of nature: Spiritual Amazonian conceptualizations of the environment](https://www.openicpsr.org/openicpsr/project/116962/version/V1/view?path=/openicpsr/116962/fcr:versions/V1/The-moral-philosophy-of-nature-Spiritual-Amazonian-conceptualizations-of-the-environment.pdf&type=file)

For #6 you should be able to see the metadata in the different tabs without downloading anything. 

6. [Data from: Monitoring the Future: A Continuing Study of American Youth (12th-Grade Survey), 2018 (ICPSR 37416)](https://www.icpsr.umich.edu/web/NAHDAP/studies/37416)

For # 7, scroll to the bottom of the page where it says "Data supplements / Supporting Information / Files in this Data Supplement:"

7. [Data from: How stereotypes impair women’s careers in science](https://www.pnas.org/content/111/12/4403/tab-figures-data)


**Returning results of breakout & take-home message** 

1. Discussion with Group of Metadata Review
1. _Take-home message:_ Metadata are hard to write but invaluable

## Part 2: Writing Metadata 

Today's session is an opportunity to start drafting the metadata for your project. Although there are links in the notes for today's session to tools that will build your metadata in machine-readable XML schema, for this class (and maybe even in most cases) a .txt or .Rmd file with information on the relevant Class Descriptors (*sensu* Michener _et al._ 1997) is all you need sufficient. To save you time, I have created metadata templates based on information from ICSPR (for social sciences) and Michener _et al._ (for biophysical sciences) that you can download and edit

### Step 1: Metadata Templates {.unnumbered}  


Download and review both templates and choose the one that is most appropriate for your project. If there is there metadata from one discipline's template that would be useful to include in yours? If so, copy the items over and save the revised file with a new (and correctly styled) name. You can also add more fields or delete any that are not relevant. Note that Table 1 in Michener _et al._ is very comprehensive and provides additional guidance on how to make sure the metadata are useful.  

**To download the metadata templates**, click the link below for your preferred format (`.txt` or `.Rmd`) and save the file in the RStudio project you've created for your Course Project. The `.txt` version can be opened and edited in any word processor, a text editor, or in R. The `.Rmd` file is an R Markdown Document.

- **Metadata Template for Social Sciences:** from ICSPR: [.txt format](https://github.com/BrunaLab/LAS6292_DataManagement/blob/955ff1d91ee9e1655019b5ced69c3676a80cdf58/instructor-materials/class-sessions/08-metadata/ICPSR_Metadata.txt) or [.Rmd format](https://github.com/BrunaLab/LAS6292_DataManagement/blob/955ff1d91ee9e1655019b5ced69c3676a80cdf58/instructor-materials/class-sessions/08-metadata/ICPSR_Metadata.Rmd). _See note below for additional info on Qualitative Data._

- **Metadata template for Biophysical Sciences**: Table 1 from Michener et al. 1997: [.txt format](https://github.com/BrunaLab/LAS6292_DataManagement/blob/955ff1d91ee9e1655019b5ced69c3676a80cdf58/instructor-materials/class-sessions/08-metadata/Michener_etal_1997_Table1.txt) or [.Rmd format](https://github.com/BrunaLab/LAS6292_DataManagement/blob/955ff1d91ee9e1655019b5ced69c3676a80cdf58/instructor-materials/class-sessions/08-metadata/Michener_etal_1997_Table1.Rmd)

- **_Note for researchers in the Humanities or those working primarily with Qualitative Data:_** The metadata required often depend on the type of material with which you work (e.g., oral history, photos, digital, printed). If your data is in this domain, you can download templates here: [Template No.1](https://docs.google.com/spreadsheets/d/1x98TWee85Gq9oas90JJYtB5DyPBkMSNEs29Mb1qyAeQ/edit#gid=0) is from UF's Samuel Proctor Oral History Project, [Template #2](https://docs.google.com/spreadsheets/d/1K9RRNWrWbK0ikQai4_baBmxobqsX6jwEsiAHVjEJRDE/edit#gid=1745662283) is a more general one from the UF Humanities Archives. You can also review the [metadata required by the Qualitative Data Repository](https://qdr.syr.edu/content/qdr-metadata-application-profile).


### Step 2: Prepare the Metadata for your project {.unnumbered}  

Start filling out the metadata requested in the template. You might want to begin by making notations on the ones for which you will have to present the range of possible values, units, the names / brands / models of equipment used to make or record measurements, etc.

### Step 3: Submission {.unnumbered}  

_You do **NOT** have to submit an assignment this week. This is a component of the Final Project for the course, so the goal for today is to jump-start your work because preparing a good metadata file takes longer than anyone anticipates. 




::: {.callout-tip}

Be sure to check the Class Notes for today's topic - they include excellent resources for preparing metadata.

:::


# Sources for Today's Session

1. ICPSR [*Guide to Social Science Data Preparation and Archiving: 
Best Practice Throughout the Data Life Cycle (6th Edition)*](https://www.icpsr.umich.edu/web/pages/deposit/guide/)

2. DataONE Community Engagement & Outreach Working Group (2017) "Metadata Management". Accessed through the Data Management Skillbuilding Hub at https://dataoneorg.github.io/Education/lessons/07_metadata/index on Aug 31, 2020

