---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified
format: pdf

---


# Automated Data Collection & Extraction - Class Exercise {#sec-automated-class}



### **Topic 1 Overview: Optical Character Recognition (OCR)** 

1. 3 folders with 9 photos, save to google drive

1. OCR to text - try doing them all, handwriting is obviously the messiest one, try doing it with your own. lets all write a text, and then try to see whow it does.  

1. no way to go directly to google sheets, need tihighlight (leave blue) to to threre icos, then open with google docs. download as text

https://www.pdf2go.com/, then compare with https://smallpdf.com/ 

1. What is OCR?

1. OCR: google, website, R
2. Data from Published Figs
3. Data Packages Govt Data via API
4. text analysis

### *Topic 2 Overview: Topic*  

Image is from: Pereira, Thales Augusto Zamberlan. (2018). Poor Man's Crop? Slavery in Brazilian Cotton Regions (1800-1850). Estudos Econômicos (São Paulo), 48(4), 623-655. https://doi.org/10.1590/0101-41614843tzp


### Breakout & Return Results 

(we did this in-class together as a live-coding-type-exercise): using [Web Plot Digitizer](https://automeris.io/WebPlotDigitizer/), we extracted data from several figures that differ in quality and content.



