---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---

# QA/QC: Reducing Error Entry, Finding and Correcting Errors 

## Reducing errors when entering data 

### Using 'Data Validation' Rules {.unnumbered}  

1. Setting up Data Validation in Microsoft Excel:  [[link to Microsoft post](https://support.microsoft.com/en-us/office/apply-data-validation-to-cells-29fecbcc-d1b9-42c1-9d76-eff3ce5f7249)] and a [tutorial video](https://www.youtube.com/watch?v=feQPLfTm6yE).

1. Setting up Data Validation in Google Sheets: 
[[link to post by Google](https://support.google.com/appsheet/answer/10107325?hl=en)] and a [tutorial video](https://www.youtube.com/watch?v=EgvSqLHRfVM)

### Data entry with 'Text-to-Speech' {.unnumbered}  

#### MS Excel (& other MS programs) {.unnumbered}  

1. Converting text to speech in Excel for Microsoft 365, Excel 2010-2021 [[link]](https://support.microsoft.com/en-us/office/converting-text-to-speech-in-excel-3f2ca8c0-90e2-4391-8e69-573832ea7300). 
1. Microsoft for Mac: Hear selected text read aloud from Excel, Word, Power Point, and Outlook [[link](https://support.microsoft.com/en-gb/office/hear-selected-text-read-aloud-ce9fb073-2a4d-44d2-95f7-6a532f0ab112)].  See also _'System Preferences->Accessibility'_

1. Video Tutorials  
* [Tutorial Video 1](https://youtu.be/5ZOsMe0aPt8). This will allow you to select rows or columns of Excel and have them read back to you. 
* [Tutorial Video 2](https://youtu.be/q6LOhQThvB8): it's not as thorough, but it is a bit easier to see the menu
* [Tutorial Video 3](https://youtu.be/DSltR90mkgc). Because why not a third one?

1. If you are typing up written observations or field notes, the NY Times Wirecutter team thinks the [Dictation tool in MS Word](https://support.microsoft.com/en-us/office/dictate-your-documents-in-word-3876e05f-3fcc-418f-b8ab-db7ce0d11d3c) is the best way transcribe your written notes. It requires an internaet connection to use, but [according to their review](https://www.nytimes.com/wirecutter/reviews/best-dictation-software/) "it handles medical terms and less-common words correctly more than most competing tools. It supports 34 languages, includes commands for punctuation, emoji, and other commonly used special characters, and allows you to format and navigate text with spoken commands."

#### Text-to-Speech in Google Docs {.unnumbered}  


1. If you prefer working in Google Docs you can do the same thing. [This article](https://www.businessinsider.com/how-to-make-google-docs-read-to-you) will show you how. You can also watch [this tutorial video](https://youtu.be/3UmI5wo5kHg).

### Better still: 'speak-on-enter' to confirm data values as entered {.unnumbered}

1. Speak-on-enter [[tutorial:]](https://www.makeuseof.com/how-to-get-microsoft-excel-speak-aloud/)

### Speech-to-Text for keyboardless data entry  {.unnumbered}

1. Google Sheets: [Typing with your voice](https://support.google.com/docs/answer/4492226?hl=en)

1. MS Word: [How to dictate documents](https://support.microsoft.com/en-us/office/dictate-your-documents-in-word-3876e05f-3fcc-418f-b8ab-db7ce0d11d3c)


### Overview of Microsoft Accessibility Tools {.unnumbered}  

1. 'Narrator' function [link](https://support.microsoft.com/en-us/windows/hear-text-read-aloud-with-narrator-040f16c1-4632-b64e-110a-da4a0ac56917)


## R Packages for Data QA/QC

1. [janitor](https://sfirke.github.io/janitor/index.html): simple functions for examining and cleaning dirty data. It was built with beginning and intermediate R users in mind and is optimized for user-friendliness. Advanced R users can already do everything covered here, but with janitor they can do it faster. (see this [mini-tutorial](https://universeofdatascience.com/how-to-clean-data-in-r/))

    * clean column names
    * remove empty rows and columns
    * remove duplicated rows

1. [cleanr](https://cran.r-project.org/web/packages/cleaner/readme/README.html). small R package for cleaning and checking data columns in a fast and easy way. 

1. [unheadr](https://unheadr.liomys.mx/): used to wrangle spreadhseets with embedded subheaders or values wrapped accross several rows (highlighting, merged cells, etc).


### **For more advanced R users:** {.unnumbered}  

1. Richard's Iannone `pointblank` R package for Data Validation and Organization of Metadata [[link](https://rstudio.github.io/pointblank/)

1. [validate](https://cran.r-project.org/web/packages/validate/vignettes/cookbook.html): designed to test data against a reusable set of data validation rules, investigate, summarize, and visualize data validation results, among other things

1. [Data Curator](https://github.com/qcif/data-curator) is a simple desktop data editor to help describe, validate and share usable open data.

1. Kim, A. Y., Herrmann, V., Barreto, R., Calkins, B., Gonzalez-Akre, E., Johnson, D. J., Jordan, J. A., Magee, L., McGregor, I. R., Montero, N., Novak, K., Rogers, T., Shue, J., & Anderson-Teixeira, K. J. (2022). Implementing GitHub Actions continuous integration to reduce error rates in ecological data collection. Methods in Ecology and Evolution, 13, 2572–2585. https://doi.org/10.1111/2041-210X.13982


## Readings & Sources

1. Campbell, J. L. _et al._ 2013. Quantity is nothing without quality: automated QA/QC for streaming environmental sensor data. BioScience, 63(7): 574-585. [link](https://www.nrs.fs.usda.gov/pubs/jrnl/2013/nrs_2013_campbell-j_002.pdf)

1. **_For more advanced users of R/Github:_** Kim, A. Y. _et al._ 2022. Implementing GitHub Actions continuous integration to reduce error rates in ecological data collection. Methods in Ecology and Evolution, 13, 2572– 2585. https://doi.org/10.1111/2041-210X.13982

1. Barchard, K. A., & Pace, L. A. (2011). Preventing human error: The impact of data entry methods on data accuracy and statistical results. Computers in Human Behavior, 27(5), 1834-1839. [link](https://www.sciencedirect.com/science/article/pii/S0747563211000707?via%3Dihub)

1. Atkinson, I. (2012). Accuracy of data transfer: double data entry and estimating levels of error. Journal of Clinical Nursing, 21(19pt20), 2730-2735.[link](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2702.2012.04353.x)

1. Goldberg, S. I., Niemierko, A., & Turchin, A. (2008). Analysis of data errors in clinical research databases. AMIA Annual Symposium proceedings. AMIA Symposium, 2008, 242–246. [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2656002/)

1. DataONE Education Module: Data Quality Control and Assurance. DataONE. Retrieved Nov12, 2012. From http://www.dataone.org/sites/all/documents/L05_DataQualityControlAssurance.pptx 

