---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---
# Reproducibile Data Cleanup with R  {#sec-reproducibility}

## Set up an RStudio Project and install the relevant packages

1. File -> New Project
1. Name the Project as follows: `las_demo`
1. Create the following three folders: 

   `data_raw`  
   `data_clean`  
   `code`  

    You can create these in the folder using your operating systems "create folder" option **_or_** you can create within R studio using the `files` tab

1. Install libraries, load libraries, and run verify they work by running a few commands

<!-- ::: {.content-visible when-format="html"} -->
<!-- #| message: false -->
<!-- #| echo: false -->
<!-- #| results: hide -->
<!-- #| eval: false -->

<!-- ```{r} -->
<!-- # Use the tab to install package `dadjokeapi`.  -->
<!-- # You could also do the following: -->
<!-- install.packages("dadjokesapi") -->
<!-- install.packages("tidyverse") -->
<!-- # load the library -->
<!-- library(dadjokeapi) -->
<!-- # run a command -->
<!-- groan() -->
<!-- ``` -->

<!-- ::: -->



<!-- ::: {.content-visible when-format="pdf"} -->

<!-- ```{r} -->

<!-- # library(plotly) -->
<!-- # library(ggplot2) -->
<!-- # # Use the tab to install package `dadjokeapi`.  -->
<!-- # # You could also do the following: -->
<!-- # install.packages("dadjokesapi") -->
<!-- # install.packages("tidyverse") -->
<!-- # # load the library -->
<!-- # library(dadjokeapi) -->
<!-- # # run a command -->
<!-- # groan() -->
<!-- ``` -->

<!-- ::: -->


## Gather the Raw Data to be corrected

Save your original (aka 'raw' or 'dirty') data files in the `data_raw` folder.


::: {.callout-important}

1. Never make changes to the original file of dirty/raw data. Never. **NEVER**. Always import the uncorrected original data file, make corrections using a script, and then save a new, clean file.   

2. _Annote your code with reminders for future you:_ the # symbol (aka pound, hash tag) allows you to make comments in the script explaining what different sections or commands do. Annotate your scripts with lots of details on what different commands do, what is being done in each section, even links to websites you used to figure stuff out. Remember: ABA _(always be annotating)_. 

:::


## _Take your data from `messy` to `clean` in these 6 steps:_  

 1. Familiarize yourself with the data set
 2. Check for potential errors. These can be structural errors (e.g., misaligned columns, duplicated rows/columns, missing values), data entry errors, or measurement errors. Decide how you will flag and deal with them.
 4. Decide how to deal with missing values
 5. Identify ways to simplify data values (i.e., codes, abbreviations) and column headings
 6. Write code to load the 'raw' data file file, implement your corrections/changes, and save the 'clean' version of the data.
 
 _Things to look out for:_ Make a list of the what you think needs to be corrected and the steps necessary to identify and implement each correction. Some of the things to look out for include: 
    
 * Numeric values stored as character data types
 * Factors stred as characters
 * Duplicate rows
 * Spelling mistakes
 * inconsistent formatting (eg., codes, capitalizations)
 * White spaces
 * Missing data
 * Zeros instead of null values
 * Special characters (e.g. commas in numeric values instead of decimals)
 * column headings with spaces between words or that start with numerals 
  
Remember, _the characteristics of clean data set include:_ 

 * Free of duplicate rows/values
 * Error-free (correct misspellings, eliminate special characters)
 * correct data type for analysis
 * outliers identified and dealt in the correct way
 * “tidy" data structure



::: {.callout-tip}

## When working with multiple files, should you correct _before_ or _after_ combining? 

We often need to combine multiple files with the same kind of data (i.e., surveys conducted in Year 1 and in Year 2, each of which are recorded in their own .csv file). Is it more efficient to correct each file first, then combine them, or combine first and _then_ correct? 

It depends and can vary from one project to another. Make an outline of the different steps and corrections to be made to each file and see if you can decide which is more efficient. Note that there might be different ways to do the same thing, this outline will help figure out which is best. For instance you could: 

  >**_Option 1_**   
    1. Import table 1   
    2. Correct column headings in Table 1  
    3. Import table 2  
    4. Correct column headings in Table 2  
    5. Bind Table 1 and Table 2 Together  

  >**_but this is less efficient than..._** 

  >**_Option 2_**  
    1. Import table 1  
    2. Import table 2   
    3. Bind Table 1 and Table 2 Together   
    4. Correct the column headings in the Table    

:::

## Tools & Resources

1. These introductions to R and R Studio were made by Professor Ethan White (UF-WEC). They are a good overview of some R basics.  

      * [Intro to R and RStudio](https://www.youtube.com/watch?v=zqUQL8OOtMQ).
      * [Navigate R and RStudio web page](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html)
      * [Intro to R Packages](https://www.youtube.com/watch?v=NAArCsmztOI)
      * [Expressions and Variables in R](https://www.youtube.com/watch?v=BFVX0CKY67g&feature=emb_title)
      
1. The Carpentries' R workshops (self-paced or taught in-person) are excellent, I use many of their materials in class: 
  
    * [R for Social Scientists](https://datacarpentry.org/r-socialsci/)
    * [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.org/R-ecology-lesson/)

1. Software Carpentry lesson on [Project Management with R Studio](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/) 

1. Hadley Wickham wrote a book on using the tidyverse and the [online version is FREE](https://r4ds.had.co.nz/). This is a phenomenal resource on using R to import, tidy, and visualize data. 

2. [RStudio Cheat Sheets](https://rstudio.com/resources/cheatsheets/): help with commands for using the different `tidyverse` packages, RStudio shortcuts and tricks, help with R commands, and more. You definitely want the ones for Data Import, Work with Strings, Factors, Data Transformation, and Base R.

3. Where and How to ask for help  

    * Hadley Wickham's advice on [how to write a good reproducible example]((http://adv-r.had.co.nz/Reproducibility.html)) for getting help with R
    * [how to post good questions on StackOverflow](https://www.r-bloggers.com/2011/01/three-tips-for-posting-good-questions-to-r-help-and-stack-overflow/)
    * The UF [R-users listserv](http://www.r-gators.com/listserv/) is *very* user friendly and a great place to post requests for help. 

1. [Ten simple rules for biologists learning to program](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005871)

4. Lot's more on the course's ['Resources' page](https://las6292.netlify.app/docs/resources/) 

# Additional (interesting) Reading

1. Lewis, Keith P., Eric Vander Wal, and David A. Fifield. 2018. Wildlife biology, big data, and reproducible research. Wildlife Society Bulletin 42(1): 172-179.  

1. White EP, Baldridge E, Brym ZT, Locey KJ, McGlinn DJ, Supp SR.  2013.  Nine simple ways to make it easier to (re)use your data. Ideas in Ecology and Evolution. 6(2):1-10.  

1. [The humanities have a ‘reproducibility’ problem](https://talkinghumanities.blogs.sas.ac.uk/2019/07/09/the-humanities-have-a-reproducibility-problem/)

1. [The humanities do not need a replication drive](https://www.cwts.nl/blog?article=n-r2v2a4&title=the-humanities-do-not-need-a-replication-drive)

1. [Reproducible Research: A primer for the social sciences](http://benmarwick.github.io/CSSS-Primer-Reproducible-Research)

1. [Replicability and replication in the humanities](https://researchintegrityjournal.biomedcentral.com/articles/10.1186/s41073-018-0060-4)

1. [Towards reproducible science in the digital humanities](https://dhh.uni.lu/2020/05/19/towards-reproducible-science-in-the-digital-humanities-how-to-publish-your-data-and-code-alongside-your-research-with-the-help-of-zenodo/)

1. [The possibility and desirability of replication in the humanities](https://www.nature.com/articles/s41599-018-0149-x)

1. [Reproducible Research: A Retrospective](https://www.annualreviews.org/doi/10.1146/annurev-publhealth-012420-105110#_i18)

**_For when you feel more comfortable with R and programming_**

1. Bryan, J. (2018). Excuse me, do you have a moment to talk about version control? The American Statistician, 72(1), 20-27.

1. Wilson, Greg, Jennifer Bryan, Karen Cranston, Justin Kitzes, Lex Nederbragt, and Tracy K. Teal. Good enough practices in scientific computing. PLoS Computational Biology 13, no. 6 (2017): e1005510.  


<!-- 4. [Reproducible Research in the Humanities](https://www.slideshare.net/IainEmsley/reproducible-research-in-the-humanities) -->
<!-- 4. https://oxford.universitypressscholarship.com/view/10.1093/oso/9780190670412.001.0001/oso-9780190670412-miscMatter-11 -->
<!-- 1. [Reproducible Data Science](https://ecorepsci.github.io/reproducible-science/)  -->


