---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---

# Breakout: TRANSCRIPTION 

We will try transcribing audio recorded in different languages using different online services; note that not all languages will be available in all services. 

## STEP 1. Sign up for an account 

Sign up for accounts with the following transcription services. You can cancel the accounts if you think you won't need them afterwards. Additional details and links to tutorials are available on the _Resources_ page.

1. [Otter.ai](https://otter.ai/login).

2. [Happy Scribe](https://www.happyscribe.com/)

3. [IBM Watson](https://www.ibm.com/products/speech-to-text), go to the [Demo Site](https://stt-demo-app.258kpouwgi7s.us-south.codeengine.appdomain.cloud/demos/live/stt-demo/self-service/home). note the "detect multiple speakers" option.

4. MS Word (for Commercial Clients): Instructions [here](https://support.microsoft.com/en-us/office/transcribe-your-recordings-7fc2efec-245e-45f0-b053-2a97531ecf57). 
  
  - Transcription of you speaking (Word Desktop or Online): Go to Home > Dictate Box > Transcribe. The Settings wheel allows you to choose the micriphone and language.
  
  - Transcription from audio file (Word Online): Go to Home > Dictate Dropdown Arrow > Transcribe. A side panel will open, follow the prompts to upload the audio file and choose options. 
  
5. Speech-to-text [with Google Docs](https://newsinitiative.withgoogle.com/resources/trainings/fundamentals/voice-typing-transcribe-audio-using-google-docs/)
  
## STEP 2: Sample Transcriptions

1. Download the following audio files. Note that the link takes you to the page where the file is archived; click the 'download' button to save it to your computer.

    * [`turkish_audio.mp3`](https://github.com/BrunaLab/LAS6292_DataManagement/blob/37ebab30eb5744a2a501572cd3b7fc2772009a34/content/instructor-materials/class-sessions/11-transcription-translation/translation_audio/turkish_audio.mp3)  

    * [`spanish_audio1_voice.mp3`](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/content/instructor-materials/class-sessions/11-transcription-translation/translation_audio/spanish_audio_1voice.mp3)  

<!-- 1. `portuguese_audio.mp3`  -->
<!-- indonesian_audio.mp3 -->
<!-- mandarin1_audio.mp3 -->
<!-- mandarin2_audio.mp3 -->
<!-- english_audio.mp3   -->

2. Now try transcribing these audio files with each of the different services (note that not all services will transcribe all languages). 

3. Save the resulting transcriptions files as Google Docs or .txt files. Use the following naming convention: `transcription_[language]_[name of service]`  


## STEP 3: Translate

1. Translating these transcriptions to English with Google Docs 

2. Save with the following file names: `translation_[language]_[name of transcription service]` (e.g., `translation_spanish_happyscribe`)  

3. Paste the *translations from transcription* and the *translation from the original .txt files* (used in the translation breakout) into the [Text Comparison Website](https://www.diffchecker.com/diff). You may have to adjust the spacing in the text files to make the text align. 

## STEP 4: Discuss

1. Do the transcriptions appear accurate? 

2. What about the translations from transcriptions? Is there a loss in quality when going from audio-to-text-to-English when compared with text-to-English

3. What would be the best approach for research: 

    a. transcribing, editing the transcription, then translating, or 
    b. transcribing, translating, then correcting? 


