---
title: "Untitled"
format: html
---

Key Safety Guidelines:
Share your travel plans with your supervisor in advance.
Stay with your group and maintain communication at all times. Never work alone in the field.
Know your location and be aware of exits, landmarks, or safe zones.
Carry your ID for appropriate identification.
Wear appropriate clothing and personal protective equipment (PPE) based on the activity and environment.
Check weather conditions and be prepared for sudden changes.
Use proper handling techniques for tools, equipment, and samples.
Report any hazards, injuries, vehicle issues, or unsafe conditions immediately to your supervisor.
Follow all instructions and protocols provided during pre‑field briefings.
 
I’d like to also remind faculty, staff, and students of the following resources that are available to you.

If an injury occurs, please be sure to follow the following procedures:

- If a life-threatening injury occurs, call 911 to seek immediate medical attention
- Contact IFAS HR for assistance: 352-392-4777 or ifas-hr@ifas.ufl.edu and notify your supervisor
- Within 24 hours of the incident, the employee and/or supervisor must notify AmeriSys of the incident: Workers’ Compensation | Current Employees
https://hr.ufl.edu/working-at-uf/employee-relations/workers-compensation/


If UF/IFAS students are experiencing stress or need to speak with a counselor, contact the Resources - UF Counseling and Wellness Center (CWC) 352-392-1575. https://counseling.ufl.edu/resources/


If you are a REC graduate student, ask for Dr. Philip Daniels when calling CWC.
If faculty, staff, graduate assistants, postdoc associates, or non-student OPS employees are experiencing stress or need to speak with a counselor, please visit the Employee Assistance Program resources at https://eap.ufl.edu. 