---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---
# Efficient Data Collection  {#sec-efficient}

<!-- * **In-class Exercise:** build a better form, find error minimization -->


## Introduction

The goal of efficient data collection is **Error Reduction:**

  * At the time of data collection 
  * When transferring to electronic format

We can reduce the introduction of errors using **Process Audits** - a tool borrowed from industrial engineering that helps to identify *where* errors are likely to sneak in.

## Forms

Many data collection errors are the result of poorly designed tools for recording information. **Most people, whether they know it or not, collect data on some kind of form**. Sometimes these forms are paper, sometimes electronic. Notes scribbled on a piece of paper or MS Word document? Both are simple 'forms'. To design better forms - forms that reduce the number of errors at both the collection and entry phases - we will use some ideas from manufacturing, shipping, and design industries, along with loads of research on forms themselves.

   * **Lists**: We forget things we need, and we forget things we need to do. Lists prevent that.
   * **Automation**: When collected repeated measurements on a single thing, or the same measurement on many things, attempt to invest in automation. 
   * **Asset Management**: There is no need to have people (data collectors or study subjects) write down information you know in advance. Use things like labels & Bar/QR codes to simplify things as much as possible. 
   * **UX/UI**: The arrangement of things on a page, and the cues used to guide input, can help reduce errors and increase form completion rates. We know this thanks to websites that depend on you filling out information to get your business; they have done lots of testing to come up with forms that ensure you don't leave the site without giving them the information they need. And so with that in mind.... 

### **Lessons from UI/UX** 

Whenever possible, the instrument for recording information (e.g., form, online survey) should strive to:

1. Reduce Cognitive Overload. Keep the form simple, easy to read, and easy to follow.

2. Require writing as little as possible

  * Use labels & keep them short…
  * …and pay attention to where you put the labels
  * Use the appropriate input type and tag…
  * …and format them in helpful ways
  * Forms should be one column…
  * …Except when multi-column makes sense 
  * Group related fields
  * AVOID ALL CAPS
  * For online forms: Show all options if < 6 (unless space is limited)
  * Number questions and responses
  * Use Formatting to guide the data collectors
  * Avoid 2x-sided forms
  * Give each sheet a unique ID number
  * Add collector info


## Checklists

Another reason errors get introduced is because we fail/forget to collect the required data (an error of omission) or because the equipment used to collect the data fails or is unavailable (e.g., the recorder runs out of batteries, the recorder is left behind, the recorder is dropped in the river). _Checklists_ are an essential way of minimizing the likelihood of these data collection errors.

Checklists are easy to make and share; here as some examples of checklists made by previous courses. The RMarkdown files used to make them can be seen and edited in [this Github folder](https://github.com/BrunaLab/LAS6292_DataCourseBook/tree/11b7782cf3595203862b5bb7413ebbf18227e79c/class_materials/class_sessions/11_efficient_data_collection/class_checklists). There are also blank templates in [RMarkdown](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/checklist_template.Rmd) and [Quarto](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/checklist_template.qmd) format to make your own. 

### Example Checklists made in Prior Classes  

* First Aid Kit [pdf](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/firstaidkit_checklist.pdf), [Rmd](class_materials/class_sessions/11_efficient_data_collection/class_checklists/firstaidkit_checklist.Rmd)
* Supplies & equipment for international travel & fieldwork [pdf](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/travel_checklist.pdf), [Rmd](class_materials/class_sessions/11_efficient_data_collection/class_checklists/travel_checklist.Rmd)
* Vehicle & vessel maintenance review: [pdf](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/vehicle_vessel_checklist.pdf), [Rmd](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/vehicle_vessel_checklist.Rmd) [Rmd](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/vehicle_vessel_checklist.Rmd) 
* Surveying Farmers Project Checklist [pdf](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/farmer_surveys_checklist.pdf), [Rmd](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/farmer_surveys_checklist.Rmd) 
* Materials for rural focus groups [pdf](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/focus_grp_checklist.pdf), [Rmd](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/class_checklists/focus_grp_checklist.Rmd)


## Tools, & Resources

### Forms

1. Schiavo, F. [The bad design of everyday things #3 — Paper Forms.](https://design-nation.icons8.com/the-bad-design-of-everyday-things-3-paper-forms-bbb20ffc3c9)
1. Maloney, S. [Best Practices for PaperBased Form Design](https://pyramidsolutions.com/wp-content/uploads/2017/09/Best-Practices-for-Paper-Based-Form-Design.pdf)
1. [How to design survey forms for quick data entry](http://www.tools4dev.org/resources/how-to-design-surveys-and-forms-for-quick-data-entry/). This is a great post with suggestions on designing survey forms for work in an international / multi-language context.
1. Best Practice for Form Design: [one](https://medium.com/nextux/form-design-best-practices-9525c321d759) and [two](https://www.ventureharbour.com/form-design-best-practices/). These suggestions come from a UX-perspective for online forms, so they might seem most appropriate for online surveys. But the suggestions are really good for paper survey forms as well.
1. [make a template for data entry (form) with Excel](https://www.pryor.com/blog/ease-the-pain-of-data-entry-with-an-excel-forms-template/)
1. ['Google Forms Essential Training' ](https://careerhub.ufl.edu/classes/google-forms-essential-training/) (requires UF login)
1. [Interesting examples of poor UX practices](https://www.pinterest.es/nunile/ux-bad-practices/)
1. ['Form Design: 13 Empirically Backed Best Practices'](https://cxl.com/blog/form-design-best-practices/)
1. ['Best Practices For Mobile Form Design'](https://www.smashingmagazine.com/2018/08/best-practices-for-mobile-form-design/)
1. Software: [TapForms](https://www.tapforms.com/)
1. Software: [Jotform](https://www.jotform.com/)

### Checklists

1. Atul Gawande's [The Checklist Manifesto](http://atulgawande.com/book/the-checklist-manifesto/) 
1. Paula Rizzo's LinkedIn Course [The Power of Lists](https://www.linkedin.com/learning-login/share?forceAccount=false&redirect=https%3A%2F%2Fwww.linkedin.com%2Flearning%2Fthe-power-of-lists-to-get-stuff-done%3Ftrk%3Dshare_ent_url%26shareId%3DH2pUj81TTkicWyBeXQHdxw%253D%253D&account=41282748)
1. Clear for [iOS](https://apps.apple.com/us/app/clear-todos/id493136154) and for [Android](https://play.google.com/store/apps/details?id=com.cleartask.tasktodo.todo&hl=en_US&gl=US) 
1. [ToDoist](https://todoist.com/) especially powerful; lists can be shared with team members and sync across devices
1. [Evernote](https://evernote.com/) really more of a note-teaking app, but good for lists too
1. NYTimes Wirecutter Review of [Best To-Do List Apps](https://www.nytimes.com/wirecutter/reviews/best-to-do-list-app/)
  

### Creating and Printing Labels

1. [Avery Waterproof labels](https://www.avery.com/category/material/all/?category=waterproof-labels)
  
### QR Codes

1. Make QR Codes in Word, Powerpoint, or Excel [Tutorial #1](https://www.youtube.com/watch?v=OV9G8L7W-Rg), [Tutorial #2](https://www.youtube.com/watch?v=GadmYWAVnjE)
1. Make [QR Codes with R](https://thierryo.github.io/qrcode/) 
1. Leila Gharani: [Create QR Codes for FREE | Use Anywhere (Excel, Word & PowerPoint)]
1. [How to Create a QR Code and Use It Effectively](https://www.youtube.com/watch?v=z22UChzno9Q)
1. [Mass Generate QR Codes to Prefill Google Forms](https://www.youtube.com/watch?v=RS45HVZrnfg)
1. ['Top 10 Barcode Scanner AppsFor iPhone and Android'](https://www.barcodesinc.com/cats/barcode-scanners/apps.htm)



## Assigned Readings & Videos

1. Redman, T. 2016. Bad Data Costs the U.S. $3 Trillion Per Year. Harvard Business Review. [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Redman_2016.pdf)

1. Atul Gawande's TED Talk: [The Importance & Value of the CHECK LIST](https://www.youtube.com/watch?v=55Nc8nccPa0). Follow-up with the details in this good [animated summary](https://www.youtube.com/watch?v=bCDmDzIOZ-g).

2. Jess Stratton (LinkedIn Learning) Video Overview: [Use Google Forms to Create Surveys](https://www.linkedin.com/learning/google-sheets-advanced-tips-and-tricks/use-google-forms-to-create-surveys?u=41282748) (7 min.)

3. OPTIONAL: A more advanced, multi-video [Google Forms Essential Training Course](https://www.linkedin.com/learning/google-forms-essential-training-2/collect-data-easily-with-google-forms?u=41282748) has short (1-3 min) videos explaining each step in more detail. It's great, and only 39 min long from start to finish.

