---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified
format: pdf
---
# Efficient Data Collection  {#sec-efficient-notes}


::: callout-tip

## Objectives and Competencies:   

* Learn to evaluate data collection procedures to identify steps at which errors are likely to enter and propagate 
* Critique and improve data collection forms
* Learn to prepare and use checklists for complex procedures such as data collection

:::



## Pre-Class Preparation (Instructor):  

**Send in an email to students:  **  

  * content of any pre-class emails.

**Bring to Class:  **  

  * Snacks
  * Flip charts and markers
  * Dry write markers
  * Tent cards for student names

## Objectives and Competencies:   

* Learn to evaluate data collection procedures to identify steps at which errors are likely to enter and propagate 
* Critique and improve data collection forms
* Learn to prepare and use checklists for complex procedures such as data collection
  
## Pre-class Preparation (Students):

### **Readings**

1. Redman, T. 2016. Bad Data Costs the U.S. $3 Trillion Per Year. Harvard Business Review. [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Redman_2016.pdf)


### **Online Lectures:**  

1. Atul Gawande's TED Talk: [The Importance & Value of the CHECK LIST](https://www.youtube.com/watch?v=55Nc8nccPa0). Follow-up with the details in this good [animated summary](https://www.youtube.com/watch?v=bCDmDzIOZ-g).

2. Jess Stratton (LinkedIn Learning) Video Overview: [Use Google Forms to Create Surveys](https://www.linkedin.com/learning/google-sheets-advanced-tips-and-tricks/use-google-forms-to-create-surveys?u=41282748) (7 min.)

3. OPTIONAL: A more advanced, multi-video [Google Forms Essential Training Course](https://www.linkedin.com/learning/google-forms-essential-training-2/collect-data-easily-with-google-forms?u=41282748) has short (1-3 min) videos explaining each step in more detail. It's great, and only 39 min long from start to finish.


## Class Outline

<!-- ```{r timer, echo=FALSE} -->
<!-- t1_overview <- 20 -->
<!-- breakout1 <- 15 -->
<!-- breakout1_return <-15 -->
<!-- t2_overview <- 30 -->
<!-- snack_break <- 10 -->
<!-- breakout2 <- 45 -->

<!-- total_time <- t1_overview +  -->
<!--   t2_overview +  -->
<!--   breakout1 +  -->
<!--   breakout1_return +  -->
<!--   snack_break +  -->
<!--   breakout2  -->

<!-- time_remain <- 180 - total_time -->
<!-- ``` -->


### **Topic 1 Overview: Intro to Efficient Data Collection** 
<!-- (`r t1_overview` min) -->


The goal of efficient data collection is **Error Reduction:**

  * At the time of data collection 
  * When transferring to electronic format

We can reduce the introduction of errors using **Process Audits** - a tool borrowed from industrial engineering that helps to identify *where* errors are likely to sneak in.

### Breakout & Return Results 

1. **Breakout 1: ** Process Audit of Field Work


1. **Part 2:** Forms
<!-- (`r breakout1` min) -->

Many data collection errors are the result of poorly designed tools for recording information. **Most people, whether they know it or not, collect data on some kind of form**. Sometimes these forms are paper, sometimes electronic. Notes scribbled on a piece of paper or MS Word document? Both are simple 'forms'. To design better forms - forms that reduce the number of errors at both the collection and entry phases - we will use some ideas from manufacturing, shipping, and design industries, along with loads of research on forms themselves.

   * **Lists**: We forget things we need, and we forget things we need to do. Lists prevent that.
   * **Automation**: When collected repeated measurements on a single thing, or the same measurement on many things, attempt to invest in automation. 
   * **Asset Management**: There is no need to have people (data collectors or study subjects) write down information you know in advance. Use things like labels & Bar/QR codes to simplify things as much as possible. 
   * **UX/UI**: The arrangement of things on a page, and the cues used to guide input, can help reduce errors and increase form completion rates. We know this thanks to websites that depend on you filling out information to get your business; they have done lots of testing to come up with forms that ensure you don't leave the site without giving them the information they need. And so with that in mind.... 


1. **Breakout 2: ** Process Audit of Data Collection Forms

  * Look over these forms and conduct a process audit. Where do you think errors are most likely to sneak in?

1.  **Returning results & Take-home message: Lessons from UI/UX**  
<!-- (`r breakout1_return` min)**  -->
<!-- (`r t2_overview` min): -->

Whenever possible, the instrument for recording information (e.g., form, online survey) should strive to:

1. Reduce Cognitive Overload. Keep the form simple, easy to read, and easy to follow.

2. Require writing as little as possible

  * Use labels & keep them short…
  * …and pay attention to where you put the labels
  * Use the appropriate input type and tag…
  * …and format them in helpful ways
  * Forms should be one column…
  * …Except when multi-column makes sense 
  * Group related fields
  * AVOID ALL CAPS
  * For online forms: Show all options if < 6 (unless space is limited)
  * Number questions and responses
  * Use Formatting to guide the data collectors
  * Avoid 2x-sided forms
  * Give each sheet a unique ID number
  * Add collector info



### Break 
<!-- (`r snack_break` min) -->


### In-class Assignment: Checklists
<!-- (`r breakout2` min) -->

Another reason errors get introduced is because we fail/forget to collect the required data (an error of omission) or because the equipment used to collect the data fails or is unavailable (e.g., the recorder runs out of batteries, the recorder is left behind, the recorder is dropped in the river). _Checklists_ are an essential way of minimizing the likelihood of these data collection errors.

Checklists are easy to make and share; here as some examples of checklists made by previous courses. The RMarkdown files used to make them can be seen and edited in [this Github folder](https://github.com/BrunaLab/LAS6292_DataCourseBook/tree/11b7782cf3595203862b5bb7413ebbf18227e79c/class_materials/class_sessions/11_efficient_data_collection/class_checklists). There are also blank templates in [RMarkdown](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/checklist_template.Rmd) and [Quarto](https://github.com/BrunaLab/LAS6292_DataCourseBook/blob/4574429630cbed827970ad366004d5f390ab0934/class_materials/class_sessions/11_efficient_data_collection/checklist_template.qmd) format to make your own. 


Now lets implement some of the things we've learned. Create a Checklist Assignment
OR data collection revision.
<!-- 1. Conduct a Process Audit of your personal data collection sheet. (If you do not have one of your own, you can do the assignment with the "Line Transect Sheet” used in class) -->
<!-- 2. Redo your paper data sheet based on your process audit -->
<!-- 3. Create an electronic version of the data sheet using Google Forms -->
<!-- 4. When done, submit the following via canvas: -->

<!--    * the original form -->
<!--    * the revised form -->
<!--    * A link to the google form -->
    


### Grading Rubric: 

**50:** Ways errors can get incorporated have been identified; revised form and google doc use UI/UX principles to reduce most data recording errors.  
**35:** Some (but not all) ways that errors can get incorporated have been identified; revised form and google doc use UI/UX principles to reduce some of the potential data recording errors.  
**20:** Few of the ways errors can be included are identified; data collection still likely to be error-prone and inefficient.  


### Free Time

There are min remaining that can be used to -----
<!-- `r time_remain` -->



