---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---
# Paperless Data Collection  {#sec-paperless}

## Recommended Platform: EpiCollect

1. EpiCollect [Homepage](https://five.epicollect.net/)
1. Download the app for [Apple iOS](https://apps.apple.com/us/app/epicollect5/id1183858199) and [Android Phones])
1. [User's guide](https://docs.epicollect.net/)
1. [Intro to EpiCollect 5](https://kaltura.uconn.edu/playlist/dedicated/1_14lpwsw0/1_fmj06huc)  
1. [Creating an EpiCollect PROJECT](https://kaltura.uconn.edu/media/Creating+an+Epicollect+5+Project/1_853ybdbf)  
1. [Creating a FORM for your Epicollect Project](https://kaltura.uconn.edu/media/Creating+a+Form+in+Epicollect+5/1_inr7wxq8)  
1. [Collecting data in EpiCollect with your phone or tablet](https://kaltura.uconn.edu/media/Collecting+Data+With+Epicollect+5/1_kgzfddtp)  

1. Aanensen DM, Huntley DM, Feil EJ, al-Own F, Spratt BG (2009) EpiCollect: Linking Smartphones to Web Applications for Epidemiology, Ecology and Community Data Collection. PLoS ONE 4(9): e6968. [link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006968)

## Paid platforms for paperless data collection

1. [Fulcrum](https://www.fulcrumapp.com/); [link to post](https://gadgets360.com/science/features/fulcrum-app-science-fieldwork-data-collection-2294662) describing how it was used by an NGO.
1. [ODK](https://getodk.org)


## Useful smartphone apps for fieldwork

1. Lists of useful apps for data collection in the field: Start with the [Bruna Lab Super-List](https://brunalab.github.io/apps_for_fieldwork/) _(if you want to suggest any additions to the list please do so [here](https://github.com/BrunaLab/apps_for_fieldwork/issues))_. You can also check [[list 2]](https://www.teamscopeapp.com/mobile-data-collection-guide/7-mobile-data-collection-apps-for-field-research), [[list 3]](https://www.researchgate.net/post/Please-could-you-indicate-some-useful-android-apps-for-Ecology-Forestry-or-Environment), [[list 4]](https://writingfornature.wordpress.com/2012/08/17/tools-for-the-modern-primate-apps-for-field-work/), [[list 5]](https://ayrnstories.wordpress.com/2017/08/09/apps-in-ecological-research/), and [[list 6]](https://www.researchgate.net/post/What_essential_android_apps_should_a_field_biologist_know_about)
1. [Research at Home: Using a Smartphone for Data Collection](https://www.societyforscience.org/research-at-home/using-smartphone-for-data-collection/)  
1. [Streamlining Field Data Collection with Mobile Apps](https://eos.org/science-updates/streamlining-field-data-collection-mobile-apps)


## Google Sheets

1. [Using IFTTT with Google Sheets](https://www.linkedin.com/learning/google-sheets-advanced-tips-and-tricks/use-ifttt-with-google-sheets?u=41282748) (LinkedIn Learning Course, requires UF login).

## Mobile Form Design 

1. [Best Practices for the design of mobile forms](https://www.smashingmagazine.com/2018/08/best-practices-for-mobile-form-design/)
1. [Optimal design of text fields in sheets](https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03)

## Barcode Scanner Apps

1. [Top 10 barcode scanner apps for iPhone and Android](https://www.barcodesinc.com/cats/barcode-scanners/apps.htm)
1. [Comparison of top free barcode and QR code scanner apps](https://www.qr-code-generator.com/blog/free-barcode-scanner-app/)


## Photos as Paperless Data Collection

1. Organizing Photos and annotating photos with [Tropy](https://tropy.org). Open source;  Allows export of notes and metadata to CSV, JSON, etc. 


## DIY

1. Sometimes to go paperless you can hack the tools you use: [Send measurements from digital calipers to Excel Sheet](https://www.notion.so/Hacking-Digital-Calipers-3ee7726f11ca431694dc70a1977516e4)  

## Additional Reading

1. [Keep calm and go paperless: Electronic lab notebooks can improve your research](https://openworking.wordpress.com/2019/07/05/keep-calm-and-go-paperless-electronic-lab-notebooks-can-improve-your-research/)

1. [NOAA Pathways to paperless Data Collection](https://www.fisheries.noaa.gov/feature-story/pathway-paperless-data-collection)

1. Thieler ER, Zeigler SL, Winslow LA, Hines MK, Read JS, Walker JI (2016) Smartphone-Based Distributed Data Collection Enables Rapid Assessment of Shorebird Habitat Suitability. PLoS ONE 11(11): e0164979. [link](https://doi.org/10.1371/journal.pone.0164979)

1. Teacher, A. G., Griffiths, D. J., Hodgson, D. J., & Inger, R. (2013). Smartphones in ecology and evolution: a guide for the app-rehensive. Ecology and evolution, 3(16), 5268–5278. [link](https://doi.org/10.1002/ece3.888)

1. Palumbo, M.J., Johnson, S.A., Mundim, F.M., Lau, A., Wolf, A.C., Arunachalam, S., Gonzalez, O., Ulrich, J.L., Washuta, A. and Bruna, E.M. (2012), Harnessing Smartphones for Ecological Education, Research, and Outreach. The Bulletin of the Ecological Society of America, 93: 390-393.  [link](https://esajournals.onlinelibrary.wiley.com/doi/10.1890/0012-9623-93.4.390)

1. Rayhan, R. U., Zheng, Y., Uddin, E., Timbol, C., Adewuyi, O., & Baraniuk, J. N. (2013). Administer and collect medical questionnaires with Google documents: a simple, safe, and free system. Applied Medical Informatics, 33(3), 12-21. [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3884902/) 

1. Moylan, C. A., Derr, A. S., & Lindhorst, T. (2013). Increasingly mobile: How new technologies can enhance qualitative research. Qualitative social work: research and practice, 14(1), 36-47. [link](https://journals.sagepub.com/doi/10.1177/1473325013516988)


1. Harari, G. M., Lane, N. D., Wang, R., Crosier, B. S., Campbell, A. T., & Gosling, S. D. (2016). Using Smartphones to Collect Behavioral Data in Psychological Science: Opportunities, Practical Considerations, and Challenges. Perspectives on Psychological Science 11(6), 838-854.  








<!-- 2. Best data app for interactive voice data collection: [Magpi](https://www.magpi.com/blog/interactive-data-collection) (Web, iOS, Android) -->

