---
# author:
#   - name: Emilio M. Bruna
#     affiliations:
#       - id: uf
#       - name: University of Florida
title-block-style: default
date-modified: last-modified

---

```{r}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(kableExtra)
```


<!-- \begin{landscape} -->

```{r}

prop_or_not<-read_csv("file_formats.csv") %>% 
  replace_na(list('open source' = " "))
kbl(prop_or_not,digits = 1,
                  format = "latex",
                  align="l",
        longtable = T, 
    col.names = NULL,
                  row.names = FALSE,
                  booktabs=T,
                  linesep = "") %>%
  kable_styling(bootstrap_options = c("hover"),
                latex_options = c("scale_down"),
                full_width = F,
                font_size = 10,
                position = "left") %>% 
  column_spec(1, width = "10em") %>% 
  column_spec(2, width = "30em")  %>% 
  column_spec(3, width = "5em")  %>% 
  row_spec(1:70,hline_after=TRUE)
```
<!-- \end{landscape} -->




