---
title: "Week 2: In-Class Assignment"
mainfont: SourceSansPro
geometry: margin=1in
output:
  pdf_document: default
  html_document:
    df_print: paged
linkcolor: blue
urlcolor: blue
fontsize: 12pt
header-includes:
- \AtBeginDocument{\let\maketitle\relax}
- \pdfmapfile{+SourceSansPro.map} #there is an error with the cmpiler, needed to add this line to use sourcesanspri
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[L]{`r format(Sys.time(), '%B %Y')`}
- \fancyhead[R]{LAS 6292 Assignment, p. \thepage}
- \usepackage{parskip}
- \usepackage{xcolor}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
---

<!-- Note: to rendr as pdf delete the \newline -->
# **LAS 6292 WEEK 2 ASSIGNMENT: Data Storage and Backup** 

**This week’s assignment is designed to:** **(A)** get you thinking critically about your own data backup and security procedures, and based on that reflection **(B)** prepare a data backup plan (if you already have one you can answer the questions below based on that plan).  **The assignment comes in four parts:**   

1. Sign up for a UF Dropbox allocation: https://cloud.it.ufl.edu/collaboration-tools/dropbox/. If you are not automatically eligible to sign up, your advisor can request that you be granted an allocation: https://cloud.it.ufl.edu/media/clouditufledu/How-to-Obtain-Access-to-UF-Dropbox-for-Education.pdf. 

2. Sign up for a UF Google Suite Allocation: https://cloud.it.ufl.edu/collaboration-tools/g-suite/   

3. Briefly describe how you are adhering to the 3-2-1 backup rule for data related to your thesis. If you are not, describe how you will do so moving forward.  

4.	Prepare a brief (~1 page max) Data Backup Plan for your thesis research. Include the following information; you can respond with bullet points unless more detailed answers are needed:   

    a.	what needs to be prepared and for how long;
  
    b.	where backups are located;  
    
    c.	who can access backups and how contacted;  
  
    d.	how often data should be backed up;  
    
    e.	what kind of backups are performed;  
  
    f.	who is responsible for performing the backups;  
  
    g.	hardware and software used for performing backups;  
  
    h.	how / how often to check if backups is successful;  
  
    i.	the media are used to backup data;  
  
    j.	a list of any data that are not archived or backed up.
  

## Submission and Grading Rubric

1) Submit the Data Backup Plan document (in either `.txt` or `.pdf` format) via [Canvas](https://elearning.ufl.edu/).

2) Grading Rubric 
    * Assignment completed with thorough answers: 50
    * Most questions answered completely; some require instructor follow-up: 40
    * Many questions missing answers or answers are cursory: 30
    * Instructor follow-up required for homework submission: 20
